apiVersion: apps/v1
kind: Deployment
metadata:
  name:otukn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otukn
  template:
    metadata:
      labels:
        app: otukn
    spec:
      containers:
      - image: okteto.dev/otukn:latest
        name: otukn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2d16daf9-bbfe-480a-9cec-05e5f6ccf291"
        - name: Vless_Path
          value: "/vlcytv5"
        - name: Vmess_UUID
          value: "2d16daf9-bbfe-480a-9cec-05e5f6ccf291"
        - name: Vmess_Path
          value: "/vm6tvr566"
        - name: Share_Path
          value: "/v2link"
