apiVersion: v1
kind: Service
metadata:
  name: otukn
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "otukn"
    port: 8080
  selector:
    app:otukn
